"""Extra English content for the condition, procedure and answer pages.
Lists are in the same order as CONDITIONS and PROCS on the home page."""

CONDS = [
 dict(slug="acidity-reflux-gerd", seo="Acidity and GERD treatment",
  causes=["A weak valve between the food pipe and stomach","Large or late meals, and lying down soon after eating","Extra weight, especially around the belly","Smoking, alcohol, and some medicines","Pregnancy and hiatus hernia"],
  tests="Most people need no tests at first. An upper GI endoscopy is done if symptoms continue despite treatment, or if there are warning signs such as trouble swallowing, weight loss, vomiting blood or anaemia.",
  faqs=[["Can acidity medicines be taken for a long time?","They are safe for most people when needed, but long-term use should be reviewed by a doctor, who will usually aim for the lowest dose that controls symptoms."],
        ["Can acidity feel like heart pain?","Yes, and the two can be hard to tell apart. Chest pain with sweating, breathlessness, or pain spreading to the arm or jaw must be checked for heart problems first, as an emergency."]],
  procs=[0], guide=1, answer="when-is-acidity-serious"),
 dict(slug="h-pylori-gastritis-ulcer", seo="H. pylori, gastritis and ulcer treatment",
  causes=["H. pylori infection, often picked up in childhood","Painkillers such as ibuprofen, diclofenac and aspirin","Smoking and heavy alcohol use","Severe illness or major surgery (stress ulcers)"],
  tests="H. pylori is confirmed with a urea breath test, a stool test, or a biopsy taken during endoscopy. An endoscopy is advised for warning signs or ulcer bleeding.",
  faqs=[["Do I need a test after treatment?","Yes. A breath or stool test at least 4 weeks after finishing the antibiotics confirms the infection has cleared."],
        ["Is H. pylori infectious?","It spreads within families, mostly in childhood, through food, water and saliva. Family members without symptoms usually do not need routine testing."]],
  procs=[0,6], guide=None, answer="when-is-acidity-serious"),
 dict(slug="swallowing-difficulty", seo="Swallowing difficulty treatment",
  causes=["Narrowing (stricture) from long-standing acid reflux","Achalasia, where the food pipe muscles do not relax","Inflammation of the food pipe (eosinophilic oesophagitis)","Narrowing after swallowing acid or other chemicals, or after radiation","A growth in the food pipe"],
  tests="An upper GI endoscopy is the main test. A barium swallow or manometry, which measures the food pipe muscles, may also be needed.",
  faqs=[["Is difficulty swallowing always cancer?","No. Most causes are narrowings or muscle problems that can be treated. An endoscopy is still important to find the cause and rule out a growth."],
        ["Can a narrowing come back after it is widened?","Sometimes, especially with long narrowings. Repeat sessions, spaced a few weeks apart, are common and safe."]],
  procs=[0,8], guide=None, answer=None),
 dict(slug="fatty-liver", seo="Fatty liver treatment",
  causes=["Extra weight, especially fat around the belly","Type 2 diabetes and prediabetes","High cholesterol or triglycerides","Regular alcohol use","Sugary drinks, refined flour and fried food"],
  tests="Liver blood tests and an ultrasound show the fat. A liver stiffness test (elastography) or blood-based scores check whether scarring has started, which decides how closely you need follow-up.",
  faqs=[["Can thin people get fatty liver?","Yes. Many Indians develop fatty liver at a normal weight, because of belly fat and insulin resistance. It needs the same attention."],
        ["Do I need medicines for fatty liver?","Weight loss, exercise and diet are the main treatment. Medicines are used for diabetes, cholesterol and, in selected people with scarring, for the liver itself."]],
  procs=[], guide=0, answer="is-fatty-liver-reversible"),
 dict(slug="hepatitis-b-c", seo="Hepatitis B and C treatment",
  causes=["Unsafe injections and reused needles","Blood transfusions that were not screened","Mother to baby at birth (mainly hepatitis B)","Unprotected sexual contact (mainly hepatitis B)","Tattoos, piercing or dental work with unsterile tools"],
  tests="HBsAg and anti-HCV blood tests screen for infection. Viral load tests (HBV DNA, HCV RNA), liver tests and a liver stiffness test decide whether and how to treat.",
  faqs=[["Is hepatitis C curable?","Yes. Tablets taken for about 3 months cure more than 95% of people."],
        ["Can someone with hepatitis B marry and have children?","Yes. The partner should be tested and vaccinated, and the baby gets the vaccine and immunoglobulin at birth, which protects most babies."]],
  procs=[], guide=None, answer=None),
 dict(slug="jaundice", seo="Jaundice treatment",
  causes=["Hepatitis A and E from contaminated food or water","Hepatitis B, and alcohol-related liver injury","Some medicines and herbal products","A gallstone or growth blocking the bile duct","Gilbert's syndrome, a harmless inherited condition"],
  tests="Liver blood tests with bilirubin, viral markers and an ultrasound find most causes. An MRCP scan or endoscopic ultrasound is used when the bile duct may be blocked.",
  faqs=[["Should I avoid haldi, oil or salt in jaundice?","No. Normal home food with usual amounts of haldi and oil is fine. A balanced diet with enough calories helps recovery more than a boiled-food-only diet."],
        ["Is jaundice infectious?","Hepatitis A and E spread through contaminated food and water, so handwashing and clean water protect the family. Most other causes do not spread."]],
  procs=[3,2], guide=4, answer="diet-in-jaundice"),
 dict(slug="cirrhosis", seo="Liver cirrhosis treatment",
  causes=["Alcohol over many years","Fatty liver that has progressed","Hepatitis B or C","Autoimmune hepatitis","Rarer genetic and bile duct diseases"],
  tests="Blood tests, an ultrasound and a liver stiffness test assess the liver. An endoscopy checks for enlarged veins (varices) in the food pipe, and an ultrasound every 6 months screens for liver cancer.",
  faqs=[["Can cirrhosis be reversed?","Scarring usually does not fully go away, but treating the cause can stop it getting worse and sometimes improves it. In advanced cases, a liver transplant may be discussed."],
        ["Should I eat less protein?","No, unless your doctor advises it. Most people with cirrhosis need enough protein and a bedtime snack to protect their muscles."]],
  procs=[4,0], guide=5, answer=None),
 dict(slug="gallstones", seo="Gallstone and bile duct stone treatment",
  causes=["Being over 40","Women, especially after pregnancies","Extra weight or very rapid weight loss","Family history","Long fasts followed by heavy meals"],
  tests="An ultrasound finds gallbladder stones. Liver tests, an MRCP scan or endoscopic ultrasound check for stones that have slipped into the bile duct.",
  faqs=[["Can gallstones be dissolved with medicine?","Rarely. Medicines work only for a few small stones and they often return, so surgery is the usual treatment for stones that cause pain."],
        ["Do silent gallstones need an operation?","Usually not. Stones found by chance that cause no symptoms are generally watched."]],
  procs=[3,2], guide=None, answer=None),
 dict(slug="pancreatitis", seo="Pancreatitis treatment",
  causes=["Gallstones","Alcohol","Very high triglycerides","Some medicines","Smoking, and in chronic pancreatitis, genetic factors and tropical pancreatitis"],
  tests="Blood amylase or lipase and an ultrasound confirm an attack. A CT scan, MRCP or endoscopic ultrasound shows complications and the cause.",
  faqs=[["Can pancreatitis come back?","Yes, if the cause continues. Removing the gallbladder after gallstone pancreatitis and stopping alcohol and smoking greatly reduce the risk."],
        ["Can pancreatitis cause diabetes?","Yes. Repeated damage in chronic pancreatitis can reduce insulin, so blood sugar is checked regularly."]],
  procs=[2,3], guide=6, answer=None),
 dict(slug="pancreatic-cysts", seo="Pancreatic cyst evaluation",
  causes=["Fluid collections (pseudocysts) after pancreatitis","Serous cysts, which are almost always harmless","Mucinous cysts, some of which can change over time","Cysts linked to the pancreatic duct (IPMN)"],
  tests="A CT or MRI scan shows the cyst. Endoscopic ultrasound gives a closer view and can sample the fluid with a fine needle to identify the type.",
  faqs=[["Is a pancreatic cyst cancer?","Most are not. A few types can turn into cancer over years, which is why the type and size decide whether to watch it or treat it."],
        ["How often do I need scans?","It depends on the cyst type and size. Small, harmless-looking cysts may need a scan every one to two years."]],
  procs=[2], guide=None, answer=None),
 dict(slug="ibs-irritable-bowel-syndrome", seo="IBS treatment",
  causes=["An over-sensitive gut-brain connection","A past stomach infection (post-infectious IBS)","Stress, anxiety and poor sleep","Certain foods that ferment in the gut","Changes in gut bacteria"],
  tests="IBS is diagnosed from the symptoms, with simple blood and stool tests and a celiac test when needed. A colonoscopy is advised for warning signs or new symptoms after 45.",
  faqs=[["Is IBS dangerous?","No. It causes real symptoms but does not damage the bowel or lead to cancer."],
        ["Can IBS be cured?","There is no one-time cure, but most people improve a lot with diet changes, routine, stress care and, when needed, medicines."]],
  procs=[1], guide=2, answer=["is-ibs-dangerous","gas-and-bloating"]),
 dict(slug="ulcerative-colitis-crohns-disease", seo="Ulcerative colitis and Crohn's disease treatment",
  causes=["The immune system attacking the bowel lining","Family history","Environmental factors such as diet and smoking (for Crohn's)","Not caused by stress or food alone, though both can trigger flares"],
  tests="Colonoscopy with biopsies confirms it. Stool calprotectin, blood tests and MRI or CT scans of the small bowel show how active it is. Intestinal TB is ruled out before starting some treatments.",
  faqs=[["Is IBD the same as IBS?","No. IBD causes real inflammation and damage in the bowel; IBS does not. They are treated very differently."],
        ["Can people with IBD lead a normal life?","Yes. With regular treatment, most people work, travel and have families. Pregnancy should be planned with your doctor."]],
  procs=[1], guide=None, answer=None),
 dict(slug="constipation", seo="Constipation treatment",
  causes=["Too little fibre and water","Little physical activity","Medicines such as iron, calcium and some painkillers","Thyroid problems, diabetes and pregnancy","IBS, and problems with the pelvic floor muscles"],
  tests="Most people need no tests. Blood tests or a colonoscopy are advised for new constipation after 45, blood in the stool, weight loss or a family history of bowel cancer.",
  faqs=[["Do I need to pass stool every day?","No. Anything from three times a day to three times a week can be normal, as long as it is comfortable."],
        ["Are laxatives harmful?","Gentle laxatives are safe when needed. Strong laxatives taken daily for a long time should be reviewed with a doctor."]],
  procs=[1], guide=3, answer=["blood-in-stool-always-piles","gas-and-bloating"]),
 dict(slug="colon-polyps-colon-cancer", seo="Colon polyp removal and colon cancer screening",
  causes=["Age over 45","A parent, brother or sister with colon cancer or polyps","Smoking and obesity","Red and processed meat, and low fibre","Long-standing ulcerative colitis or Crohn's disease"],
  tests="Colonoscopy is the best test: it finds polyps and removes them at the same time. A stool test for hidden blood (FIT) is another screening option.",
  faqs=[["When should I get a colonoscopy?","Discuss it with your doctor from about 45, or about 10 years earlier than the age at which a close relative was diagnosed. Symptoms need testing at any age."],
        ["Does polyp removal hurt?","No. The bowel lining has no pain nerves, and the procedure is done under sedation."]],
  procs=[1,5], guide=None, answer="blood-in-stool-always-piles"),
]

PROCS = [
 dict(slug="upper-gi-endoscopy", seo="Upper GI endoscopy",
  uses=["Acidity or upper belly pain that does not settle","Difficulty swallowing","Vomiting blood or black stools","Unexplained anaemia or weight loss","Testing for H. pylori and celiac disease","Checking for varices in liver disease"],
  risks="Endoscopy is very safe. A mild sore throat for a day is common. Bleeding or a tear is rare, mostly when treatment is done during the test.",
  faqs=[["Can I eat after an endoscopy?","Yes, once the throat numbness wears off, usually within an hour. Start with something light."],
        ["Will I be awake?","You can choose throat spray only, or light sedation so you are drowsy and relaxed. Most people remember very little."]],
  conds=[0,1,2,6], answer="is-endoscopy-painful"),
 dict(slug="colonoscopy", seo="Colonoscopy",
  uses=["Blood in the stool","Change in bowel habit lasting weeks","Unexplained anaemia or weight loss","Checking and following up IBD","Screening for polyps and colon cancer"],
  risks="Bloating and cramps for a few hours are common. Bleeding after polyp removal or a tear in the bowel are rare.",
  faqs=[["Is the bowel preparation difficult?","The cleansing drink is the hardest part, but it is important: a clean bowel lets small polyps be seen. Follow the timing exactly."],
        ["Will I feel pain?","Usually not. It is done under sedation, and you may feel some pressure or wind afterwards."]],
  conds=[13,11,10,12], answer="is-endoscopy-painful"),
 dict(slug="endoscopic-ultrasound-eus", seo="Endoscopic ultrasound (EUS)",
  uses=["Pancreatic cysts and lumps","Bile duct stones that scans miss","Staging growths of the food pipe, stomach and pancreas","Needle samples (biopsies) from lumps and lymph nodes","Draining fluid collections after pancreatitis"],
  risks="EUS is very safe. When a needle sample or drainage is done, there is a small risk of bleeding, infection or pancreatitis.",
  faqs=[["How is EUS different from a normal endoscopy?","A normal endoscopy shows the inner lining. EUS adds ultrasound, which sees through the wall to organs and lumps next to it."],
        ["When will biopsy results come?","Usually within a week. Some special tests take longer."]],
  conds=[9,7,8,5], answer=None),
 dict(slug="ercp", seo="ERCP",
  uses=["Stones stuck in the bile duct","Blockage of the bile duct by a narrowing or growth (stenting)","Bile leaks after surgery","Stones and narrowings in the pancreatic duct"],
  risks="Pancreatitis is the most common complication, in a few out of every hundred people. Bleeding, infection and perforation are uncommon. These are explained before the procedure.",
  faqs=[["Will I need my gallbladder removed after ERCP?","Often yes. If stones came from the gallbladder, removing it prevents them coming back."],
        ["Are bile duct stents permanent?","Plastic stents are temporary and are usually changed or removed within a few months. Metal stents may stay longer."]],
  conds=[7,5,8], answer=None),
 dict(slug="variceal-banding-evl", seo="Variceal banding (EVL)",
  uses=["Preventing a first bleed from varices in cirrhosis","Stopping active bleeding from varices","Preventing repeat bleeding"],
  risks="Chest discomfort and mild pain on swallowing for a day or two are common. Bleeding from the small ulcer left after banding is uncommon.",
  faqs=[["How many sessions are needed?","Usually several, 2 to 4 weeks apart, until the veins are gone. Checks continue afterwards."],
        ["Will I also need medicines?","Often yes. Medicines that lower pressure in the liver veins (beta-blockers) are commonly used with banding."]],
  conds=[6], answer=None),
 dict(slug="polyp-removal-emr", seo="Polyp removal and EMR",
  uses=["Polyps in the large bowel","Early flat growths in the bowel, stomach or food pipe","Removing tissue in one piece for full testing"],
  risks="Bleeding during or after removal and a small tear are uncommon, and are usually managed through the scope.",
  faqs=[["Can EMR avoid surgery?","For many early growths, yes. The final plan depends on the tissue report."],
        ["Will I need another colonoscopy?","Yes. A follow-up colonoscopy is advised, usually after 1 to 3 years depending on what was removed."]],
  conds=[13], answer=None),
 dict(slug="gi-bleeding-treatment", seo="GI bleeding treatment",
  uses=["Bleeding stomach or duodenal ulcers","Bleeding from varices in liver disease","Bleeding from abnormal blood vessels","Bleeding after polyp removal"],
  risks="Most bleeding is controlled through the scope. Sometimes bleeding returns and a repeat procedure, a radiology procedure or surgery is needed.",
  faqs=[["What should I do if I vomit blood or pass black stools?","Go to the nearest emergency department straight away, or call 112. Do not wait to see if it settles."],
        ["Can the bleeding come back?","Sometimes. Treating the cause, such as clearing H. pylori or stopping painkillers, greatly lowers the risk."]],
  conds=[1,6], answer=None),
 dict(slug="peg-feeding-tube", seo="PEG feeding tube",
  uses=["After a stroke that affects swallowing","Head, neck or food pipe cancers","Long-term neurological conditions","Anyone who cannot swallow safely for weeks or more"],
  risks="Infection at the skin site, leakage or a blocked tube can happen and are usually easy to treat. Serious complications are uncommon.",
  faqs=[["Can the patient still eat by mouth?","It depends on how safe swallowing is. Some people take small amounts by mouth along with tube feeds."],
        ["How long does the tube last?","Many months. It can be changed when needed, and removed if swallowing recovers."]],
  conds=[2], answer=None),
 dict(slug="dilatation-stenting", seo="Dilatation and stenting",
  uses=["Narrowings of the food pipe from acid, chemicals, surgery or radiation","Achalasia (balloon dilatation)","Blocked bile ducts","Growths blocking the food pipe or bowel, to relieve symptoms"],
  risks="Chest discomfort is common for a day. A tear is uncommon. Stents can occasionally move or block and need adjustment.",
  faqs=[["How many dilatations will I need?","Some narrowings need one session; others need several, a few weeks apart."],
        ["Is a stent permanent?","It depends on the reason. Stents for growths often stay; others are removed after some weeks."]],
  conds=[2,7], answer=None),
]

# Longer answer pages. Each section is (heading, paragraphs) or (heading, ["- item", ...]).
ANSWERS = [
 dict(slug="is-fatty-liver-reversible", q="Is fatty liver reversible?", cond=3,
  desc="Yes, early fatty liver can be reversed. How much weight to lose, what to eat and when to get checked, explained by gastroenterologist Dr. Kshitij Lochab.",
  short="Yes. In its early stages, fatty liver can be fully reversed. Losing 7 to 10% of your body weight, being active every day and cutting sugar, refined flour and alcohol can clear the extra fat and even reverse early scarring.",
  sections=[
   ("How much weight do I need to lose?",["Studies show that losing about 5% of body weight reduces liver fat, 7% can calm the inflammation, and 10% can reverse early scarring. For someone who weighs 80 kg, that means 4 to 8 kg.","Aim for half to one kilo a week. Very fast weight loss can worsen the liver and cause gallstones."]),
   ("What helps the most",["- Cutting sugary drinks, sweets and packaged juices","- Replacing maida with whole grains, millets and dal","- Vegetables or salad with every meal","- At least 150 minutes of brisk walking a week, which helps even before the weight falls","- Avoiding alcohol completely"]),
   ("When it may not fully reverse",["Once fatty liver has progressed to heavy scarring (cirrhosis), the scarring usually does not go away completely. Even then, the same steps slow the damage and protect the liver. This is why finding it early matters."]),
   ("How do I know if my liver is scarred?",["Fatty liver usually causes no symptoms, so tests are needed. Liver blood tests, an ultrasound and a liver stiffness test (elastography) show how much fat and scarring there is, and guide how often you need follow-up."]),
  ]),
 dict(slug="is-endoscopy-painful", q="Is endoscopy painful?", cond=None, proc=0,
  desc="Most people find endoscopy much easier than expected. What you feel, sedation options, how long it takes and recovery, explained by Dr. Kshitij Lochab.",
  short="No, for most people. An endoscopy takes 10 to 15 minutes and is done with a throat spray or light sedation. You may feel some pressure or the urge to burp, but not pain, and most people go home within an hour or two.",
  sections=[
   ("What you feel during the test",["With throat spray, the back of the throat goes numb. You may gag briefly as the thin tube goes in, and then feel pressure or fullness as air opens the stomach. Breathing stays normal throughout.","With light sedation, you are drowsy and relaxed, and most people remember very little."]),
   ("Is a colonoscopy painful?",["A colonoscopy is usually done under sedation. You may feel some cramping or wind, which settles soon after. The bowel cleansing the day before is often the hardest part."]),
   ("Is a biopsy painful?",["No. The stomach and bowel lining have no pain nerves, so taking small tissue samples cannot be felt."]),
   ("After the test",["- A mild sore throat for a day is common","- Eat once the throat numbness wears off, usually within an hour","- If you had sedation, do not drive for the rest of the day and have someone accompany you"]),
  ]),
 dict(slug="diet-in-jaundice", q="What should I eat in jaundice?", cond=5,
  desc="What to eat during and after jaundice, and which common food myths to ignore. Practical advice from gastroenterologist Dr. Kshitij Lochab.",
  short="Eat normal, balanced home food with enough calories, and drink plenty of clean water. There is no need to avoid haldi, oil or salt used in normal cooking. Avoid alcohol completely, and do not take herbal remedies unless your doctor approves them.",
  sections=[
   ("Good choices",["- Dal, rice, roti, khichdi and vegetables","- Curd, buttermilk and fruits","- Small meals every few hours if appetite is poor","- Plenty of boiled or filtered water"]),
   ("Myths to ignore",["- Boiled food only: this causes weakness and slows recovery","- No haldi or oil: normal cooking amounts are fine","- Sugarcane juice or special home remedies cure jaundice: they do not, and unclean juice can spread infection"]),
   ("What to avoid",["- Alcohol, completely, until your doctor says the liver has recovered, and longer for some causes","- Herbal products and medicines not prescribed by your doctor","- Street food and water from unsafe sources"]),
   ("Find the cause",["Jaundice is a sign, not a disease. Most cases from hepatitis A or E settle in weeks, but a blocked bile duct, hepatitis B or a medicine reaction need specific treatment. Get liver tests and an ultrasound early."]),
  ]),
 dict(slug="is-ibs-dangerous", q="Is IBS dangerous?", cond=10,
  desc="IBS is uncomfortable but does not damage the bowel or cause cancer. Which symptoms are not IBS and need tests, explained by Dr. Kshitij Lochab.",
  short="No. IBS causes real pain, bloating and bowel trouble, but it does not damage the bowel, cause bleeding or lead to cancer. The important thing is to make sure the symptoms really are IBS.",
  sections=[
   ("Why IBS feels so bad",["In IBS, the nerves linking the gut and the brain become over-sensitive. Normal amounts of gas and normal bowel movements are felt as pain, bloating or urgency. Stress and some foods make it worse."]),
   ("Signs that are not IBS",["These need proper tests:","- Blood in the stool","- Weight loss without trying","- Symptoms that wake you at night","- Fever or anaemia","- New symptoms after age 45, or a family history of bowel cancer or IBD"]),
   ("What helps",["- Meals at regular times","- Gentle fibre such as oats and isabgol","- Finding trigger foods with a short diary, often onion, garlic, rajma or milk","- Better sleep, exercise and stress care","- Medicines for pain, constipation or loose motions when needed"]),
  ]),
 dict(slug="blood-in-stool-always-piles", q="Is blood in the stool always piles?", cond=13,
  desc="Blood in the stool is often piles or a fissure, but not always. Which signs need a colonoscopy, explained by gastroenterologist Dr. Kshitij Lochab.",
  short="No. Piles and fissures are the most common causes of bright red blood, but polyps, inflammation of the bowel and colon cancer can bleed too. Any rectal bleeding should be checked once by a doctor, at any age.",
  sections=[
   ("Common causes",["- Piles: bright red blood on the paper or in the pan, usually painless","- Fissure: bleeding with sharp pain while passing stool","- Polyps or colon cancer: often no pain, sometimes dark or mixed blood","- Colitis or IBD: blood with loose motions or mucus"]),
   ("Signs that need a colonoscopy",["- Age over 45 with new bleeding","- Change in bowel habit for more than 3 weeks","- Weight loss, tiredness or anaemia","- A close relative with colon cancer","- Blood mixed with stool, or dark red blood"]),
   ("Black stools are different",["Black, sticky, tar-like stools usually mean bleeding higher up, from the stomach. With weakness or dizziness, this is an emergency."]),
   ("Why it is worth checking",["Colon cancer is increasingly seen in younger adults. Caught early, or as a polyp, it can be removed during a colonoscopy, often without surgery."]),
  ]),
 dict(slug="when-is-acidity-serious", q="When is acidity a sign of something serious?", cond=0,
  desc="Most acidity is simple reflux, but some signs need an endoscopy. Warning signs and when to see a gastroenterologist, explained by Dr. Kshitij Lochab.",
  short="Most acidity is simple reflux that settles with habit changes and short courses of medicine. See a doctor if it happens twice a week or more, lasts beyond 2 to 4 weeks, or comes with any warning sign.",
  sections=[
   ("Warning signs",["- Difficulty or pain while swallowing","- Weight loss without trying","- Vomiting blood or black, tar-like stools","- Anaemia or unusual tiredness","- Persistent vomiting","- New symptoms starting later in life"]),
   ("Rule out the heart first",["Chest pain with sweating, breathlessness, or pain spreading to the arm or jaw can be a heart attack, even when it feels like acidity. Go to an emergency department straight away."]),
   ("What a gastroenterologist checks",["An upper GI endoscopy shows inflammation, ulcers, a hiatus hernia or Barrett's oesophagus, and tests for H. pylori. It takes about 10 to 15 minutes."]),
   ("Simple steps that help",["- Dinner at least 3 hours before bed","- Smaller meals","- Raising the head end of the bed","- Losing extra weight","- Less tea, coffee, fried food, smoking and alcohol"]),
  ]),
 dict(slug="gas-and-bloating", q="Why do I get so much gas and bloating?", cond=10,
  desc="Gas and bloating are common and usually harmless. Everyday causes, simple fixes and the signs that need a check-up, explained by Dr. Kshitij Lochab.",
  short="Gas and bloating are very common and are usually not a sign of serious disease. Swallowed air, some foods, constipation and a sensitive gut (IBS) are the usual causes. See a doctor if it is new, keeps getting worse, or comes with weight loss, vomiting or blood in the stool.",
  sections=[
   ("Common causes",["- Eating fast, talking while eating, chewing gum and fizzy drinks, which add swallowed air","- Foods that make more gas in the gut, such as rajma, chana, cabbage and onion, or a lot of new fibre at once","- Milk and milk products, in people who do not digest lactose well","- Constipation, which traps gas behind hard stool","- IBS, where the gut feels normal amounts of gas more strongly"]),
   ("What usually helps",["- Eat slowly, at regular times, and do not lie down right after meals","- Cut down on fizzy drinks and chewing gum","- Keep a food diary for a week to find your own triggers, instead of stopping many foods at once","- Add fibre slowly and drink enough water","- A 15-minute walk after meals helps gas move along"]),
   ("Signs that need a check-up",["See a doctor if bloating comes with:","- Weight loss without trying","- Vomiting, or difficulty swallowing","- Blood in the stool, or black stools","- A swollen belly that keeps growing instead of coming and going","- New symptoms after age 45, or a family history of bowel or ovarian cancer"]),
   ("When it is urgent, and which tests help",["Severe belly pain with a hard, swollen belly, repeated vomiting, or not passing gas or stool is an emergency. Call 112 or go to the nearest emergency department.","Most people with gas and bloating need no tests. If symptoms continue or warning signs are present, your doctor may suggest blood tests, an ultrasound, a test for H. pylori, or an endoscopy or colonoscopy."]),
  ]),
]
